# Generated by Django 5.0 on 2024-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
